import React from 'react';


// metadata

export const metadata = {
  title: 'Public Policy App',
  description: 'Generated by Next.js',
};


export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode;
}) {
  return (
      <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className="font-sans bg-gray-100">
      {children}
      </body>
      </html>
  );
}